### ISSUE TITLE
PackSquash filters out "assets/minecraft/shaders/include" folder. Version 0.3.0

### ISSUE THREAD

**Issue by sj-dan** [ComunidadAylas/PackSquash#44] opened 2022-01-10 05:01 UTC
**Describe the bug**

When trying to "obfuscate" my pack, I keep getting the following errors.

```
[Render thread/ERROR]: Could not open GLSL import shaders/include/extra.glsl: minecraft:shaders/include/extra.glsl
[Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
Caused by: yk: Invalid shaders/core/particle.json: Couldn't compile fragment program (pack.zip, particle) : 2(1) : error C0000: minecraft:shaders/include/extra.glsl
0(4) : error C1503: undefined variable "make_emissive"
0(4) : error C1503: undefined variable "remap_alpha"
Caused by: java.io.IOException: Couldn't compile fragment program (pack.zip, particle) : 2(1) : error C0000: minecraft:shaders/include/extra.glsl
0(4) : error C1503: undefined variable "make_emissive"
0(4) : error C1503: undefined variable "remap_alpha"
```

**To Reproduce**
1. Create a resource pack with the directory `assets/minecraft/shaders/include`, and put any file with extension `.glsl` in the folder.
2. Run it through PackSquash (options don't matter).
3. Apply in-game
4. It will fail, saying "Resource reload failed in the top right."

**Expected behavior**
PackSquash should include the `assets/minecraft/shaders/include` directory and its contents in the generated ZIP file.

**Comment by AlexTMjugador** [comment] 2022-01-10 08:24
Thank you for your useful bug report! I can confirm that it happens with the latest v0.3.0 release.

However, after the v0.3.0 release was made, I've added support for include shaders in .glsl files. You can get an unstable PackSquash build with this and other fixes from GitHub Actions. This link will do (it might be necessary to be logged in to see the download links in the "Artifacts" section): [https://github.com/ComunidadAylas/PackSquash/actions/runs/1675306550](https://github.com/ComunidadAylas/PackSquash/actions/runs/1675306550)

The latest unstable builds still have some noteworthy limitations when optimizing shaders, though:

- Preprocessor directives are only supported at the external declaration position (i.e. top level of a shader file). This means that PackSquash will spew errors if you use `#moj_import` inside a function, for example.
- Included shaders (.glsl files) are parsed as translation units (i.e. standalone, normal vertex or fragment shaders). Therefore, included shaders must only contain declarations. They can't contain expressions that would only be valid inside declarations, such as `var = 3`. Such included shaders are only valid if they are always `#moj_import`'ed within a declaration (function, data type definition, etc.), which is currently not possible due to the previous point, but it's still worth keeping in mind.

These shortcomings should be addressed at some point, but the proper way to do so is not trivial and will not come in the next patch release, v0.3.1.

Please let me know if using a newer build and staying away from using `#moj_import` as stated helped you.

**Comment by sj-dan** [comment] 2022-01-10 08:29
> Thank you for your useful bug report! I can confirm that it happens with the latest v0.3.0 release.
> 
> 
> 
> However, after the v0.3.0 release was made, I've added support for include shaders in .glsl files. You can get an unstable PackSquash build with this and other fixes from GitHub Actions. This link will do (it might be necessary to be logged in to see the download links in the "Artifacts" section): [https://github.com/ComunidadAylas/PackSquash/actions/runs/1675306550](https://github.com/ComunidadAylas/PackSquash/actions/runs/1675306550)
> 
> 
> 
> The latest unstable builds still have some noteworthy limitations when optimizing shaders, though:
> 
> 
> 
> - Preprocessor directives are only supported at the external declaration position (i.e. top level of a shader file). This means that PackSquash will spew errors if you use `#moj_import` inside a function, for example.
> 
> - Included shaders (.glsl files) are parsed as translation units (i.e. standalone, normal vertex or fragment shaders). Therefore, included shaders must only contain declarations. They can't contain expressions that would only be valid inside declarations, such as `var = 3`. Such included shaders are only valid if they are always `#moj_import`'ed within a declaration (function, data type definition, etc.), which is currently not possible due to the previous point, but it's still worth keeping in mind.
> 
> 
> 
> These shortcomings should be addressed at some point, but the proper way to do so is not trivial and will not come in the next patch release, v0.3.1.
> 
> 
> 
> Please let me know if using a newer build and staying away from using `#moj_import` as stated helped you.

So I actually managed to fix the issue by building the program from the git repo. I managed to get it working, but there was 1 thing that really puzzled me for a bit. If I ran `cargo build`, PackSquash would be really slow. However, running `cargo build --release` says the built program is now "optimized", and it makes a **world** of difference. It reduced my texture pack completion time from ~50 minutes to <5 minutes!

**Comment by AlexTMjugador** [comment] 2022-01-10 08:39
By building the program from source you've made your own unstable build, so it makes sense that doing so fixed your problems :)

`cargo build` compiles Rust packages in debug mode, without any compiler optimizations enabled. These builds are only meant to be used for development, because they are faster to generate and easier to debug, but much slower and bigger. The `--release` switch is needed to build in release mode, which enables compiler optimizations and several other things better suited for actual usage. These compiler optimizations are expected to improve performance a lot.

I'm closing this issue as resolved. It still was useful for me to document outside Discord the limitations that shader optimization currently has. Thank you again for filling this bug report ❤️

**Closed by AlexTMjugador** 2022-01-10 08:39 UTC
Labels: bug
