### ISSUE TITLE
Train models are not working correctly due to shaders

### ISSUE THREAD

**Issue by Garbageskull** [ComunidadAylas/PackSquash#334] opened 2024-10-29 00:39 UTC
### Distribution

Windows executable

### Bug description

The error occurs when installing shaders, namely, the texture disappears from the hit box of trains and is attached to the player's body 
![2024-10-29_03 34 23](https://github.com/user-attachments/assets/3db185e3-f6f4-42fd-8307-0697fb6ecca4)
![2024-10-29_03 34 27](https://github.com/user-attachments/assets/308ac07f-8ba0-4884-8442-f8282ea54106)

### Reproduction steps

Lunch 
shader off train models correct
shaders on models train incorrect 

### Expected behavior

After I encountered this bug, I went to YouTube to find out what the problem was, to the surprise of other people, the mod worked perfectly with shaders

**Comment by AlexTMjugador** [comment] 2024-10-30 17:39
Thank you for the bug report, but I'm afraid that in its current state I'm not capable of troubleshooting it.

Could you please provide the following additional information to help with that?

- Which mod provides these trains, perhaps MTR? Please specify both the mod version and the game version.
- Does this issue occur with specific trains only?
- If the train is from a resource pack, could you share that pack?
- Are the shaders part of a resource pack, or are they distributed in another format?
- Could you share the shaders where this issue occurs?
- If the shaders are provided by a resource pack, does it make a difference whether PackSquash optimizes that pack?
- Does [updating PackSquash to an unstable build](https://github.com/ComunidadAylas/PackSquash/wiki/Getting-started#-unstable-builds) help?

**Comment by AlexTMjugador** [comment] 2024-11-15 10:36
If shader processing is indeed the cause of this issue, it’s likely that the latest unstable builds, which include significant improvements to shader processing, would resolve it. However, without additional input, I’m unable to investigate this issue further and will be closing it for now. If you’d like it to be revisited, feel free to provide the requested information in a comment.

**Closed by AlexTMjugador** 2024-11-15 10:36 UTC
Labels: bug
